### PR TITLE
Use protobufs for communication with apiserver

### PR DESCRIPTION
**Pull request by wojtek-t**
@bowei @thockin

### CODE REVIEW

**Comment by MrHohn** [comment]
@wojtek-t Is this critical for k8s v1.6? I just cut a new release for cluster-proportional-autoscaler yesterday, wonder if worth to cut new patch release for this.

**Comment by MrHohn** [comment]
LGTM

**Comment by wojtek-t** [comment]
@MrHohn - it would be super useful to have it for 1.6 - with JSON the load generated on apiserver in 5000-node clusters is quite significant.
How much work is with cutting a new release? Maybe I can help with that?

**Comment by MrHohn** [comment]
Thanks for the info! Cutting a new release is trivial, I'm working on it now :)

**Pull request merged**
